name: Tests

on: [pull_request]

env:
  DEFAULT_COMPOSER_FLAGS: "--prefer-dist --no-interaction --no-progress --optimize-autoloader"

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.0', '7.1', '7.2', '7.3', '7.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer update $DEFAULT_COMPOSER_FLAGS
      - name: PHP Unit tests for PHP 7.4
        run: vendor/bin/phpunit -v --coverage-clover coverage.clover
        if: matrix.php == '7.4'
      - name: PHP Unit tests for PHP 7.0 - 7.3
        run: vendor/bin/phpunit -v
        if: matrix.php == '7.3' || matrix.php == '7.2' || matrix.php == '7.1' || matrix.php == '7.0'
      - name: Code coverage
        run: |
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover
        if: matrix.php == '7.4'
        continue-on-error: true # if is fork
