name: Tests

on: [pull_request]

jobs:
  phpunit:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.1', '7.2', '7.3', '7.4', '8.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PHP
        uses: shivammathur/setup-php@2.17.1
        with:
          php-version: ${{ matrix.php }}
        env:
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v2.1.7
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --optimize-autoloader
      - name: PHP Unit tests
        run: vendor/bin/phpunit --verbose
